version: '3'

volumes:
  frontend-dist:

services:
  frontend-build:
    build: ./frontend
    container_name: vue-frontend-build
    restart: no  # 不需要一直重启，只构建一次
    volumes:
      - frontend-dist:/app/dist
    command: ["ls", "-l", "/app/dist"]

  backend:
    build: ./backend
    container_name: dotnet-backend
    restart: always
    environment:
      - ASPNETCORE_URLS=http://+:5000
    # ports:
    #   - "5000:5000"

  nginx:
    image: nginx:stable-alpine
    container_name: nginx
    restart: always
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - frontend-dist:/usr/share/nginx/html:ro  # 挂载前端构建结果
    depends_on:
      - frontend-build
      - backend
