version: '3'
services:
  frontend:
    build: ./frontend
    container_name: vue-frontend
    restart: always

  backend:
    build: ./backend
    container_name: dotnet-backend
    restart: always
    environment:
      - ASPNETCORE_URLS=http://+:5000
    ports:
      - "5000:5000"

  nginx:
    image: nginx:stable-alpine
    container_name: nginx
    restart: always
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - frontend
      - backend